### ISSUE TITLE
Merge to upstream?

### ISSUE THREAD

**Issue by timburgan** [vegardit/synology-wireguard#1]
:wave: @sebthom Is it ok to [create a PR](https://github.com/runfalk/synology-wireguard/compare/master...vegardit:synology-wireguard:master) to have all your changes merged back upstream into @runfalk's repo `runfalk/synology-wireguard`?

**Comment by sebthom** [comment]
Hi Tim, in one of the issues the repo owner stated that he is not using Synology anymore and thus the repo is dormant. Unfortunately he did not archive the project or add a notice in the main readme. So don't think creating a PR in the upstream repo will have much value since it will never get merged.
